/* Spatial screen uses official ward evidence. All points are label anchors, never GPS sites. */
'use strict';
const spatialState={p:1,mode:'median',ward:17,layer:'proximity'};
const glyph=(name)=>({arrow:'↗',next:'→',down:'↓'}[name]||'↗');
function selectedSpatial(){return (spatialState.mode==='coverage'?LOCATION_DATA.coverageScenarios:LOCATION_DATA.scenarios)[spatialState.p-1];}
function wardMap(solution,{compact=false,interactive=true,layer='proximity'}={}){
 const L=LOCATION_DATA, selected=new Set(solution.sites), allocations=new Map(solution.allocations.map(a=>[a.ward,a]));
 const colors=['#e5d260','#d8ded6','#e4e7e0','#eceee8','#f0f1ed','#f0f1ed'];
 let svg=`<svg class="ward-map ${compact?'compact-map':''}" viewBox="${L.mapViewBox}" role="img" aria-label="Nagpur final municipal wards. Highlighted areas are model-selected search wards, not store premises or delivery catchments."><defs><pattern id="atlas-grid-${compact?'mini':'full'}" width="42" height="42" patternUnits="userSpaceOnUse"><path d="M42 0H0V42" fill="none" stroke="#b9c1b7" stroke-width=".5" opacity=".24"/></pattern></defs><rect width="780" height="900" fill="url(#atlas-grid-${compact?'mini':'full'})"/>`;
 L.wards.forEach(w=>{
  const a=allocations.get(w.id),isChosen=selected.has(w.id),active=interactive&&spatialState.ward===w.id;
  const fill=layer==='population'?`hsl(76 17% ${90-(w.population-47000)/25000*25}%)`:colors[Math.min(a.hops,5)];
  svg+=`<path class="ward-shape ${isChosen?'chosen':''} ${active?'ward-active':''}" d="M${w.polygon.map(p=>p.join(',')).join('L')}Z" fill="${isChosen?'#e5d260':fill}" ${interactive?`tabindex="0" role="button" data-ward="${w.id}" aria-label="Ward ${w.id}, ${esc(w.name)}, ${number(w.population)} delimitation population"`:''}><title>Ward ${w.id} · ${esc(w.name)} · ${number(w.population)} delimitation population</title></path>`;
 });
 if(layer==='allocation'){
  L.wards.forEach(w=>{const a=allocations.get(w.id),to=L.wards[a.assigned-1];if(a.hops&&a.hops<=1)svg+=`<line class="allocation-line" x1="${w.label[0]}" y1="${w.label[1]}" x2="${to.label[0]}" y2="${to.label[1]}"/>`;});
 }
 L.wards.forEach(w=>{if(!selected.has(w.id))svg+=`<text class="ward-label" x="${w.label[0]}" y="${w.label[1]+4}">${w.id}</text>`;});
 solution.sites.forEach((id,i)=>{const w=L.wards[id-1];svg+=`<g class="map-pin" transform="translate(${w.label[0]},${w.label[1]})" ${interactive?`tabindex="0" role="button" data-ward="${id}" aria-label="Inspect search ward ${id}"`:''}><circle r="24" fill="#17362f" stroke="#f7f7f0" stroke-width="4"/><text y="5" text-anchor="middle" fill="#fff" font-size="15" font-weight="700">${id}</text></g>`;});
 return svg+`<g transform="translate(710,40)"><path d="M0 28V0L-5 12M0 0L5 12" fill="none" stroke="#51635c" stroke-width="1.4"/><text x="0" y="-10" text-anchor="middle" font-size="12" fill="#51635c">N</text></g></svg>`;
}
function atlasOverview(){
 const rows=shortlist.map((c,i)=>`<tr><td class="rank">${i+1}</td><td>${cityButton(c)}<div class="subcell">${esc(c.state)}</div></td><td>${scoreCell(c)}</td><td class="num">${lakh(c.pop)}</td><td class="num">${number(c.density)}</td><td class="num">${cr(c.model.marketBase,1)}</td><td class="num">${band(c.model.oneStoreShareLow,c.model.oneStoreShareHigh,1)}%</td><td>${presenceBadge(c)}</td></tr>`).join('');
 return head('Priority cities','Commercial comparison · 2026 planning estimates',`<button class="quiet-button" data-view="markets">All city parameters ↗</button>`)+panel('Expansion shortlist','Six commercially screened cities',`<div class="table-scroll"><table class="brief-table"><thead><tr><th>Order</th><th>City</th><th>Score /100</th><th>Population<br><small>Census 2011</small></th><th>Density<br><small>people /km² · 2011</small></th><th>City GMV /year<br><small>Model estimate</small></th><th>Share for 1 store eq.</th><th>Minutes status</th></tr></thead><tbody>${rows}</tbody></table></div>`,'','Store equivalents use peer throughput · Unconfirmed presence does not establish absence');
}
function previousAtlasOverview(){
 const lead=shortlist[0],m=lead.model,L=LOCATION_DATA,s=L.scenarios[0];
 return `<div class="atlas-heading"><div><span class="overline">EXPANSION DESK / INDIA</span><h1>Expansion priorities<span class="yellow-dot">.</span></h1></div><div class="heading-note">Research cut<br><strong>08 October 2026</strong></div></div>
 <div class="atlas-ribbon"><div><strong>${number(T.stats.markets)}</strong><span>urban markets</span></div><div><strong>${number(T.stats.rankedCandidates)}</strong><span>complete candidate scores</span></div><div><strong>${number(T.stats.presenceMarkets)}</strong><span>Minutes presence matches</span></div><span class="ribbon-note">Planning estimates<br>Official-source inputs</span></div>
 <div class="desk-layout"><section class="priority-desk"><div class="desk-title"><div><span class="overline">01 / COMMERCIAL SCREEN</span><h2>Priority cities</h2></div><button class="round-arrow" data-view="markets" aria-label="Open all markets">↗</button></div><div class="desk-column-labels"><span>Market / screening score</span><span>City GMV /yr</span></div><div class="city-watchlist">${shortlist.map((c,i)=>`<button data-city="${c.id}" class="watch-row ${i===0?'lead-row':''}"><span class="watch-rank">${String(i+1).padStart(2,'0')}</span><span class="watch-name">${esc(c.name)}<small>${score(c)} /100 <i>·</i> ${esc(c.state)}</small></span><span class="watch-value">${cr(c.model.marketBase)}<small>2026 model</small></span><span class="watch-arrow">↗</span></button>`).join('')}</div><div class="desk-note"><span class="status-square"></span><p>Minutes status unconfirmed · Entry vs infill unresolved</p></div><button class="full-link" data-view="markets">Compare city parameters <span>→</span></button></section>
 <section class="map-desk"><div class="map-desk-head"><div><span class="overline">02 / SPATIAL SCREEN</span><h2>Nagpur <span class="quiet">/ 38 wards</span></h2></div><span class="map-status">Ward-level model</span></div><div class="map-scene">${wardMap(s,{compact:true,interactive:false})}<div class="map-callout"><span>FIRST SEARCH AREA</span><strong>Ganeshpeth<br>&amp; Rambagh</strong><small>Ward 17 · preliminary</small><button data-view="locations">Explore location plan <span>↗</span></button></div><div class="map-scale-note">Final ward boundaries · 2025<br>Diagram anchors, not property coordinates</div></div><div class="map-desk-bottom"><div><b>38</b><span>candidate wards evaluated</span></div><div><b>1</b><span>proposed pilot case</span></div><button data-view="locations" aria-label="Open spatial planning">→</button></div></section></div>
 <div class="decision-strip"><div class="decision-number">01</div><div class="decision-copy"><span class="overline">PRIORITY / ${esc(lead.name.toUpperCase())}</span><h2>Review Nagpur first</h2><p>Rank 1–2 in score sensitivity · Initial decision: one-store pilot case</p></div><div class="decision-stat"><strong>${cr(m.entryBase,1)}</strong><span>annual GMV at 10% ambition</span></div><div class="decision-stat"><strong>${band(m.oneStoreShareLow,m.oneStoreShareHigh,1)}%</strong><span>share for one store equivalent</span></div><button class="solid-button" data-city="${lead.id}">Open city analysis ↗</button></div>
 <div class="reading-grid"><button data-view="city" class="reading-tile"><span>03 / CITY ANALYSIS</span><strong>City inputs &amp;<br>store thresholds</strong><i>↗</i></button><button data-view="brief" class="reading-tile"><span>04 / DECISION BRIEF</span><strong>Priority comparison &amp;<br>investment status</strong><i>↗</i></button></div>`;
}
function wardAnalysis(){
 const L=LOCATION_DATA,s=selectedSpatial(),w=L.wards[spatialState.ward-1],c=T.cities.find(c=>c.name==='Nagpur'),m=c.model;
 const chosen=s.sites.includes(w.id),a=s.allocations.find(a=>a.ward===w.id),first=L.scenarios[0],reduction=(1-s.weightedHops/first.weightedHops)*100;
 return `<div class="atlas-heading"><div><span class="overline">LOCATION INTELLIGENCE / NAGPUR</span><h1>A place to begin<span class="yellow-dot">.</span></h1></div><button class="quiet-button" id="location-method">Model details ↗</button></div>
 <div class="location-intro"><span class="status-square"></span><span><b>Ward-level search recommendations.</b> Exact premises, rents and ten-minute coverage are not yet established.</span><button data-city="${c.id}">City business case ↗</button></div>
 <div class="spatial-toolbar"><div class="spatial-budget"><span class="control-label">COMPARE NETWORKS</span><div class="segments">${[1,2,3,4].map(p=>`<button data-spatial-p="${p}" class="${spatialState.p===p?'active':''}" aria-pressed="${spatialState.p===p}">${p} ${p===1?'search area':'areas'}</button>`).join('')}</div></div><div class="spatial-objective"><span class="control-label">OBJECTIVE</span><div class="segments">${[['median','Population proximity'],['coverage','Adjacent population']].map(([mode,label])=>`<button data-spatial-mode="${mode}" class="${spatialState.mode===mode?'active':''}" aria-pressed="${spatialState.mode===mode}">${label}</button>`).join('')}</div></div></div>
 <div class="spatial-layout"><section class="spatial-map-panel"><div class="spatial-map-top"><span><strong>NAGPUR</strong> <i>Municipal boundary</i></span><div class="map-layers">${[['proximity','Proximity'],['population','Population'],['allocation','Links']].map(([k,t])=>`<button data-spatial-layer="${k}" class="${spatialState.layer===k?'active':''}" aria-pressed="${spatialState.layer===k}">${t}</button>`).join('')}</div></div><div class="large-map-wrap">${wardMap(s,{layer:spatialState.layer})}<div class="map-legend"><span><i class="legend-yellow"></i>Selected search ward</span><span><i class="legend-green"></i>Adjacent ward</span><small>${spatialState.layer==='allocation'?'Lines show assignments, not road routes.':spatialState.layer==='population'?'Darker fill = larger delimitation population.':'Proximity follows shared boundaries, not travel time.'}</small></div></div><div class="spatial-map-footer"><span>38 official ward areas · click a ward to inspect</span><span>Boundary cut: 30 SEP 2025</span></div></section>
 <aside class="location-results"><div class="result-heading"><span class="overline">${spatialState.p===1?'INITIAL SEARCH PRIORITY':'NETWORK COMPARISON'}</span><h2>${spatialState.p===1?'Begin with Ward '+s.sites[0]:s.p+' areas, evaluated together'}</h2><p>${spatialState.p===1?'A geographic starting point for premises diligence.':'Alternative footprint, not approval to open this many stores.'}</p></div><div class="site-list">${s.sites.map((id,i)=>{const site=L.wards[id-1];return `<button class="site-row ${w.id===id?'active':''}" data-ward="${id}"><span class="site-number">${String(i+1).padStart(2,'0')}</span><span><b>${esc(site.name)}</b><small>Ward ${id} · ${number(site.population)} baseline residents</small></span><span>↗</span></button>`;}).join('')}</div>
 <div class="ward-inspector"><div class="inspector-eyebrow"><span>INSPECTING WARD ${w.id}</span><span>${chosen?'SELECTED':'COMPARISON'}</span></div><h3>${esc(w.name)}</h3><div class="inspector-stat"><strong>${number(w.population)}</strong><span>delimitation population<br>not a current customer count</span></div><p>${esc(w.localities)}</p><div class="access-gate"><b>Access &amp; premises check</b><p>${esc(w.gate)}</p></div>${!chosen?`<small>Nearest selected ward in this graph: ${a.assigned} · ${a.hops} boundary transition${a.hops===1?'':'s'}.</small>`:''}</div>
 <button class="full-link" id="export-location">Download location analysis <span>↓</span></button></aside></div>
 <div class="spatial-metrics"><div><span>Population-weighted separation</span><strong>${number(s.weightedHops,2)} <small>ward transitions</small></strong><p>${spatialState.p===1?'Baseline for comparing larger networks.':number(reduction,1)+'% lower than the one-area p-median case.'}</p></div><div><span>Within selected or adjoining wards</span><strong>${lakh(s.oneHopPopulation)}</strong><p>${pct(s.withinOneHopPct)} of the delimitation baseline; not delivery coverage.</p></div><div><span>Combinations evaluated</span><strong>${number(s.configurations)}</strong><p>Every ${s.p}-ward combination. Exact within this simplified model.</p></div></div>
 <div class="spatial-bottom"><section class="network-frontier"><div class="desk-title"><div><span class="overline">INCREMENTAL NETWORK VALUE</span><h2>More reach has a cost.</h2></div></div>${networkChart()}<p>Topology improves as areas are added. The demand model supports only a conditional one-store pilot; extra areas require incremental demand and a separate cost case.</p></section><section class="investment-gate"><span class="overline">COMMERCIAL DISCIPLINE</span><h2>Space is not demand.</h2><div class="investment-row"><span>Citywide planning GMV</span><strong>${cr(m.marketBase)}</strong></div><div class="investment-row"><span>10% entrant ambition</span><strong>${cr(m.entryBase,1)}</strong></div><div class="investment-row"><span>Benchmark store equivalents</span><strong>${band(m.storeLow,m.storeHigh,2)}</strong></div><div class="investment-row"><span>Recommended initial sequence</span><strong>1 pilot → review</strong></div><p>Do not allocate citywide revenue to Ward ${s.sites[0]}. Ward-level spending, current demand and competitor coverage have not been measured.</p><div class="stress-note"><b>${L.stress.pilotRetained}/${L.stress.tests}</b><span>single-boundary disruption tests retain the first search ward. A topology sensitivity check, not road reliability.</span></div></section></div>
 <details class="location-scope"><summary>Geographic coverage of this release</summary><p>Nagpur has a complete 38-ward spatial screen. Other city dossiers retain commercial estimates and official qualitative operating evidence, but have no algorithm-selected store areas yet. The app does not invent coordinates for those cities.</p></details>`;
}
function networkChart(){
 const rows=LOCATION_DATA.scenarios;return `<div class="frontier-chart">${rows.map(s=>`<button data-spatial-p="${s.p}" aria-label="Compare ${s.p} areas"><span class="frontier-value">${number(s.weightedHops,2)}</span><div class="frontier-track"><i style="height:${s.weightedHops/rows[0].weightedHops*100}%" class="${spatialState.p===s.p?'selected':''}"></i></div><b>${s.p} ${s.p===1?'area':'areas'}</b></button>`).join('')}</div><div class="chart-unit">Population-weighted ward transitions · lower is better</div>`;
}
function spatialMethod(){
 const L=LOCATION_DATA;
 document.getElementById('method-title').textContent='Location model';
 document.getElementById('method-body').innerHTML=`<section class="method-section"><h3>What the recommendation means</h3><p>The output is a priority order for searching within municipal wards. Map markers sit on the source map's ward labels. They are not latitude/longitude coordinates, demand centroids, available buildings, leased stores or service catchments.</p><p>The official final map and final notification use the same 30 September 2025 ward scheme. Each of the 38 population values was compared across both documents; their sum is ${number(L.population)}. This is the delimitation baseline, not a new 2026 enumeration. It differs from the city dossier's Census urban agglomeration, so the two populations are never substituted.</p></section>
 <section class="method-section"><h3>Active model: exact discrete location-allocation</h3><div class="formula-line">p-median: minimise Σᵢ populationᵢ × minⱼ∈S dᵢⱼ<br>Maximal adjacency: maximise Σᵢ populationᵢ × 1[minⱼ∈S dᵢⱼ ≤ 1]<br>|S| = p; p ∈ {1, 2, 3, 4}<br>dᵢⱼ = shortest path across shared ward boundaries</div><p>All wards are demand units and candidate search areas. A shared boundary costs one transition; within a ward costs zero. This is an explicitly simplified topological screen, not a road-network approximation in minutes. Ward shapes are traced from the official raster map; digitisation is analyst-derived. Edge contacts are reviewed against that map. No map pixels are converted into kilometres.</p><p>All combinations are enumerated: 38, 703, 8,436 and 73,815. Each demand ward is assigned once to its closest selected ward. Ties go to the lower ward number. For p-median ties, higher adjacent population wins; for coverage ties, lower weighted separation wins. Remaining ties use ascending ward IDs.</p><p>Administrative wards have similar populations by design, uneven area and major transport barriers. This can favour central wards. Equal-ward weights and one-boundary-at-a-time failures are computed as sensitivity checks. They do not correct unknown local demand or road impedance. Store counts above one are comparisons, not funded recommendations.</p></section>
 <section class="method-section"><h3>Commercial and operational constraints</h3><p>The independent city model proposes a one-store pilot only under its stated market-share, basket-value and national-throughput assumptions. It does not prove that the selected ward can support that store. Current rents, fit-out cost, occupied household spending, rival service polygons, permission for use, rider access and peak road travel times are not established.</p><p>A premises-level model should use capacitated facility location with verified candidate parcels, demand cells, peak-time road paths and store costs. Set delivery time as picking + dispatch + travel + doorstep time, not travel alone. Capacity and overlap must be enforced before claiming ten-minute coverage. That road-and-property model is not represented as completed here.</p></section>
 <section class="method-section"><h3>Verification and source access</h3>${L.sources.map(s=>`<div class="source-row"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></div>`).join('')}<p>Locality names for selected wards were checked against the final Marathi notification and the ward descriptions. Earlier draft ward populations are excluded where they differ from the final scheme. Municipal maps provide administrative boundaries; they do not approve dark-store use.</p><button class="export-button" id="export-location">Download calculations &amp; checks ↓</button></section>`;
 document.getElementById('method-dialog').showModal();
}
document.addEventListener('click',e=>{
 const el=e.target.closest('[data-spatial-p],[data-spatial-mode],[data-spatial-layer],[data-ward],#location-method,#export-location');if(!el)return;
 if(el.dataset.spatialP){spatialState.p=Number(el.dataset.spatialP);spatialState.ward=selectedSpatial().sites[0];render();}
 if(el.dataset.spatialMode){spatialState.mode=el.dataset.spatialMode;spatialState.ward=selectedSpatial().sites[0];render();}
 if(el.dataset.spatialLayer){spatialState.layer=el.dataset.spatialLayer;render();}
 if(el.dataset.ward){spatialState.ward=Number(el.dataset.ward);render();}
 if(el.id==='location-method')spatialMethod();
 if(el.id==='export-location'){download('Minutes-Nagpur-location-screen-2026-10-08.json',JSON.stringify(LOCATION_DATA,null,2),'application/json');toast('Ward recommendations and model checks exported.');}
});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('svg [data-ward]')){e.preventDefault();spatialState.ward=Number(e.target.dataset.ward);render();}});
