/* Public satellite context and locality-level competitor records. No inferred store GPS. */
const LOCAL_COMPETITION={
 Nagpur:[{brand:'Instamart',area:'Nagpur catalogue',status:'Catalogue only',url:'https://www.swiggy.com/instamart/city/nagpur/b/grameen',limits:'Official city catalogue; physical store address and service coverage unverified.'},{brand:'Blinkit',area:'Dharampeth / Gokulpeth / Ram Nagar',status:'Reported service neighbourhoods',url:'https://www.linkedin.com/posts/adhindsa_blinkit-is-now-live-in-nagpur-we-opened-activity-7243144777775415296-7igu',limits:'Historical company-leader announcement; no store address.'},{brand:'Zepto',area:'Nagpur establishment',status:'Historical record · June 2025',url:'https://cdn.zeptonow.com/investors/documents/Zepto%20Limited%20-%20UDRHP-I.pdf',limits:'UDRHP-I, PDF page 588. No address or current operating status. Checked by PDF text and second PDF extraction.'}],
 Visakhapatnam:[{brand:'Blinkit',area:'Ramnagar',status:'Launch-store locality reported',url:'https://www.linkedin.com/posts/adhindsa_blinkit-is-now-live-in-visakhapatnam-activity-7246047475159998464-4lqE',limits:'Historical company-leader announcement. Store locality only; no building coordinate. Search excerpt and direct post agree.'}],
 Kochi:[{brand:'Blinkit',area:'Kaloor',status:'Launch-store locality reported',url:'https://www.linkedin.com/posts/adhindsa_blinkit-is-now-live-in-kochi-and-just-in-activity-7236620582706917376-Xyvm',limits:'Historical company-leader announcement. Store locality only; no building coordinate. Search excerpt and direct post agree.'}]
};
function localCompetition(name){
 const records=LOCAL_COMPETITION[name]||[];
 return `<div class="local-evidence"><span class="overline">LOCALITY EVIDENCE</span>${records.length?records.map(r=>`<div class="local-evidence-row"><b>${esc(r.brand)} · ${esc(r.area)}</b><small>${esc(r.status)}</small></div>`).join(''):'<div class="local-evidence-row"><b>Store localities not verified</b></div>'}<small>Exact addresses and current coverage unverified</small></div>`;
}
function mapCityTabs(){return `<div class="city-pills map-city-tabs" aria-label="City maps">${shortlist.map(c=>`<button data-map-city="${esc(c.name)}" aria-pressed="${mapState.cityName===c.name}" class="${mapState.cityName===c.name?'active':''}">${esc(c.name)} <small>${c.name==='Nagpur'?'WARD MODEL':'WARDS'}</small></button>`).join('')}</div>`;}
function geographicEvidence(name){
 if(name==='Nagpur'){competitorEvidence();return;}
 const g=PRIORITY_MAPS.cities.find(x=>x.name===name),records=LOCAL_COMPETITION[name]||[];
 document.getElementById('method-title').textContent=name+' / map evidence';
 document.getElementById('method-body').innerHTML=`<section class="method-section"><h3>Satellite context · 2021</h3><p>ESA WorldCover Sentinel-2 annual composite and classification. The rectangle is a viewing extent, not a city boundary. Land-cover colours describe mapped surface types, not current housing occupancy, income or store suitability.</p><p><a href="https://esa-worldcover.org/en/data-access" target="_blank" rel="noopener">ESA data and licence ↗</a></p><p>View reference: ${esc(g.anchorName)}. ${esc(g.coordinateCheck)}</p><a href="${esc(g.url)}" target="_blank" rel="noopener">Official geographic reference ↗</a></section><section class="method-section"><h3>Competitor locality evidence</h3>${records.length?records.map(r=>`<div class="source-row"><b>${esc(r.brand)} · ${esc(r.area)}</b><small>${esc(r.limits)}</small><a href="${esc(r.url)}" target="_blank" rel="noopener">Company announcement ↗</a></div>`).join(''):'<p>No official physical-store locality established in this review.</p>'}<p>No store coordinates or service polygons are inferred from locality names. Public evidence is incomplete and does not establish competitor absence.</p></section>`;
 const w=CITY_WARDS[name];
 document.getElementById('method-body').innerHTML=`<section class="method-section"><h3>${w.count} wards · ${esc(w.status)}</h3><p>${esc(w.registration)} ${esc(w.checks)}</p>${name==='Visakhapatnam'?'<p>The downloadable GVMC source is labelled proposed. It has not been reconciled with a final gazette map and is not presented as the current adopted boundary.</p>':''}<a href="${esc(w.source)}" target="_blank" rel="noopener">Official ward map ↗</a>${w.countSource?` · <a href="${esc(w.countSource)}" target="_blank" rel="noopener">Independent official count check ↗</a>`:''}</section>`+document.getElementById('method-body').innerHTML;
 document.getElementById('method-body').innerHTML+=`<section class="method-section"><h3>Imagery display</h3><p>1800 × 1800 source request; native Sentinel-2 source resolution is unchanged. Four map extents now fit the complete published ward geometry. No-data pixels are transparent over a blue-grey cartographic background; no replacement satellite pixels are generated. Imagery and ward maps have different dates.</p></section>`;
 const n=CITY_NETWORKS.cities[name];
 document.getElementById('method-body').innerHTML+=`<section class="method-section"><h3>One-to-four-area model</h3><p>${esc(CITY_NETWORKS.method)} ${esc(CITY_NETWORKS.limitations)}</p><p>All four solutions are ${n.scenarios.every(s=>s.solverStatus===0)?'solver-certified optima for the stated mathematical model':'labelled by their solver status in the export'}. Independent enumeration checks the one- and two-area optima, and all four Vadodara cases. Every objective is recomputed from nearest-area distances.</p><p>Mapped built-up area: ${number(n.builtKm2,2)} km². Independent polygon rasterisers differ by at most ${number(n.maxRasterizerDifferencePp,2)} percentage points in the built-up share. This checks calculation consistency, not ground truth. Satellite weights are not population, income or orders.</p><a href="https://esa-worldcover.org/en/data-access" target="_blank" rel="noopener">Official classification data and methodology ↗</a></section>${name==='Vadodara'?`<section class="method-section"><h3>Vadodara alignment check</h3><p>${w.alignmentCheck.insidePublishedWard} of ${w.alignmentCheck.points} independent municipal plot coordinates fall inside their published ward. All ${w.alignmentCheck.within150mOfPublishedWard} lie inside or within 150 metres of it. These points were not used to fit the map. This is a ward-membership check, not a survey-accuracy guarantee; no check points covered Ward 19.</p><a href="${w.alignmentCheck.source}" target="_blank" rel="noopener">Municipal coordinate register ↗</a></section>`:''}`;
 document.getElementById('method-dialog').showModal();
}
function priorityNetwork(){return CITY_NETWORKS.cities[mapState.cityName].scenarios[(mapState.networkP||1)-1];}
function priorityNetworkControls(){
 const p=mapState.networkP||1;
 return `<div class="map-room-command"><div class="map-room-network"><span class="control-label">SELECT NETWORK</span><div class="segments">${[1,2,3,4].map(n=>`<button data-network-p="${n}" aria-pressed="${p===n}" class="${p===n?'active':''}">${n} ${n===1?'area':'areas'}</button>`).join('')}</div></div><span class="network-basis">Built-up land proximity · 2021</span></div>`;
}
function priorityNetworkPins(g,z){
 const w=CITY_WARDS[g.name];return priorityNetwork().areas.map((id,i)=>{const ward=w.wards.find(d=>d.id===id),p=cityWardPoint(g,ward.anchor);return `<g class="priority-network-pin" transform="translate(${p.join(',')}) scale(${1/z})" role="button" tabindex="0" data-priority-ward="${id}" aria-label="Search area ${i+1}: ward ${id}, ${esc(ward.name)}"><path d="M0 19C-10 7-23-7-23-20a23 23 0 1146 0C23-7 10 7 0 19Z" fill="#f3d55b" stroke="#213c2e" stroke-width="2.5"/><text y="-12" text-anchor="middle" fill="#17362b" font-size="20" font-weight="700">${id}</text><rect x="-56" y="24" width="112" height="28" rx="3" fill="#17362b"/><text y="44" text-anchor="middle" fill="#fff4c1" font-size="14">AREA ${i+1}</text></g>`;}).join('');
}
function priorityNetworkResults(){
 const n=CITY_NETWORKS.cities[mapState.cityName],w=CITY_WARDS[mapState.cityName],s=priorityNetwork();
 return panel('Network comparison','Built-up land weighted · straight-line screen',`<div class="benefit-grid"><div><span>Search areas</span><strong>${s.p}</strong><small>${s.areas.map(id=>'Ward '+id).join(' · ')}</small></div><div><span>Mean separation</span><strong>${number(s.meanSeparationKm,2)} km</strong><small>Between ward anchors · not road distance</small></div><div><span>Reduction vs one area</span><strong>${pct(s.reductionVsOnePct)}</strong><small>Geographic comparison · not delivery savings</small></div></div><div class="table-scroll"><table><thead><tr><th>Network</th><th>Selected wards</th><th>Mean separation</th><th>Reduction vs 1 area</th></tr></thead><tbody>${n.scenarios.map(r=>`<tr class="${r.p===s.p?'base-row':''}"><td><button class="small-link" data-network-p="${r.p}">${r.p} ${r.p===1?'area':'areas'}</button></td><td>${r.areas.map(id=>`<button class="small-link" data-priority-ward="${id}">${id} · ${esc(w.wards.find(x=>x.id===id).name)}</button>`).join(' / ')}</td><td>${number(r.meanSeparationKm,2)} km</td><td>${pct(r.reductionVsOnePct)}</td></tr>`).join('')}</tbody></table></div><div class="panel-foot">Built-up includes roads and industry · No household-demand, traffic or rent model · Areas are not approved store sites</div>`);
}
function cityWardPoint(g,p){return [40.5+1519*(p[0]-g.bbox[0])/(g.bbox[2]-g.bbox[0]),1519*(g.bbox[3]-p[1])/(g.bbox[3]-g.bbox[1])];}
function cityWardDrawing(g,w,z){
 if(!mapState.boundaries)return '';
 const paths=w.wards.map(d=>{const selected=mapState.priorityWard===d.id,chosen=priorityNetwork().areas.includes(d.id);const path=d.rings.map(r=>'M'+r.map(p=>cityWardPoint(g,p).map(x=>x.toFixed(2)).join(',')).join('L')+'Z').join('');return `<path class="priority-ward ${selected?'is-selected':''}" d="${path}" fill-rule="evenodd" fill="${chosen?'#f4d96855':selected?'#ffffff20':'#fff8cc08'}" stroke="${chosen?'#ffe079':selected?'#ffffff':'#fff8df'}" stroke-width="${(chosen?4.5:selected?3.5:2.2)/z}" role="button" tabindex="0" data-priority-ward="${d.id}" aria-label="Inspect ward ${d.id}: ${esc(d.name)}"><title>${d.id} · ${esc(d.name)}</title></path>`;}).join('');
 const labels=w.wards.map(d=>{const p=cityWardPoint(g,d.anchor);return `<text class="geo-ward-label priority-label" x="${p[0]}" y="${p[1]}" font-size="${22/z}" stroke-width="${3/z}">${d.id}</text>`;}).join('');
 return paths+labels;
}
function priorityCityMap(){
 const g=PRIORITY_MAPS.cities.find(x=>x.name===mapState.cityName),c=shortlist.find(x=>x.name===g.name),m=c.model,w=CITY_WARDS[g.name];
 const reference=false,layer=mapState.base==='landcover'?'landcover':'satellite',z=mapState.zoom,v=[mapState.cx-800/z,mapState.cy-759.5/z,1600/z,1519/z].join(' '),selected=w.wards.find(x=>x.id===mapState.priorityWard);
 const tabs=[['satellite','Satellite'],['landcover','Land cover']];const network=priorityNetwork();
 const drawing=reference?`<rect width="1600" height="1519" fill="#fff"/><image href="${w.referenceImage}" x="0" y="0" width="1600" height="1519" preserveAspectRatio="xMidYMid meet"/>`:`<rect x="-1600" y="-1519" width="4800" height="4557" fill="#395963"/><image href="${g[layer]}" x="40.5" y="0" width="1519" height="1519"/>${cityWardDrawing(g,w,z)}${priorityNetworkPins(g,z)}`;
 return `<div class="atlas-heading map-room-heading"><div><span class="overline">STORE LOCATION ANALYSIS</span><h1>${esc(c.name)} map</h1></div><button class="quiet-button" data-city-map-evidence="${esc(c.name)}">Map details ↗</button></div>${mapCityTabs()}${priorityNetworkControls()}
 <div class="ward-map-summary"><span><b>${w.count}</b> wards</span><span>${esc(w.status)}</span><span>${w.wards.length?'Select a ward to inspect':'Separate municipal ward map'}</span></div>
 <div class="map-room"><section class="geo-surface"><div class="geo-top"><div class="geo-tabs">${tabs.map(([key,name])=>`<button data-map-base="${key}" aria-pressed="${reference?key==='wards':layer===key}" class="${(reference?key==='wards':layer===key)?'active':''}">${name}</button>`).join('')}</div><span>${reference?'VMC / 2022':'ESA / 2021'}</span></div><div class="geo-canvas"><svg id="priority-city-map" viewBox="${v}" role="group" aria-label="${esc(c.name)} ${reference?'municipal ward map':'satellite map with '+w.count+' published ward boundaries'}; pins identify search wards, not store premises">${drawing}</svg><div class="geo-controls"><button data-map-action="in" aria-label="Zoom in">+</button><button data-map-action="out" aria-label="Zoom out">−</button><button data-map-action="fit" aria-label="Fit whole city">⌂</button></div><div class="geo-pan"><button data-map-action="north" aria-label="Pan north">↑</button><button data-map-action="west" aria-label="Pan west">←</button><button data-map-action="east" aria-label="Pan east">→</button><button data-map-action="south" aria-label="Pan south">↓</button></div><div class="geo-corner"><b>N ↑</b><span>${reference?'Published municipal map':w.wards.length?'Search areas · not store premises':'Satellite context · wards in separate tab'}${g.name==='Visakhapatnam'?'<br>Proposal boundaries; final-map match unverified':''}</span></div></div>
 <div class="geo-layer-bar">${w.wards.length?`<button class="quiet-button" data-map-action="wards" aria-pressed="${mapState.boundaries}">${mapState.boundaries?'Hide':'Show'} ward boundaries</button>`:''}<span>${reference?'19 administrative wards · original map geometry':layer==='landcover'?'Red: built-up · blue: water · dark green: trees':g.noDataPct?'Blue-grey: no satellite data':'Sentinel-2 annual composite · 2021'}</span></div><div class="geo-attribution">${reference?'© Vadodara Municipal Corporation · Published ward map':'© ESA WorldCover project 2021 / Contains modified Copernicus Sentinel data (2021) · <a href="https://esa-worldcover.org/en/data-access" target="_blank" rel="noopener">CC BY 4.0</a>'}</div></section>
 <aside class="geo-dossier"><div class="geo-dossier-heading"><span class="overline">${selected?'SELECTED WARD':'WARD COVERAGE'}</span><h2>${selected?'Ward '+selected.id:w.count+' wards'}</h2><span class="small-status">${selected?esc(selected.name):esc(w.status)}</span></div><div class="geo-inspector">${selected?`<button class="full-link" data-priority-focus="${selected.id}">Focus on ward ↗</button>`:''}<div class="compact-case"><span>City GMV /year · model</span><strong>${cr(m.marketBase,1)}</strong></div><div class="compact-case"><span>Attractiveness</span><strong>${score(c)} /100</strong></div><div class="compact-case"><span>Initial commercial case</span><strong>1-store pilot</strong></div><div class="compact-case"><span>Share for one store equivalent</span><strong>${band(m.oneStoreShareLow,m.oneStoreShareHigh,1)}%</strong></div><div class="compact-case"><span>Network comparison</span><strong>${network.p} search ${network.p===1?'area':'areas'}</strong></div><div class="compact-case"><span>Weighted straight-line separation</span><strong>${number(network.meanSeparationKm,2)} km</strong></div><div class="compact-case"><span>Ward demand / site fit</span><strong>Unverified</strong></div></div><div class="geo-competition">${localCompetition(c.name)}<button data-city-map-evidence="${esc(c.name)}">Location evidence ↗</button></div><button class="full-link" data-city="${c.id}">Open city analysis ↗</button></aside></div>
 <div class="geo-decision-strip"><div><span>Population · Census 2011</span><strong>${lakh(c.pop)}</strong><small>${c.geotype==='UA'?'Urban agglomeration':'Town'} · separate from ward geography</small></div><div><span>Historical city density</span><strong>${number(c.density)}<em>people /km²</em></strong><small>City / UA average</small></div><div><span>Orders /day at 10% share</span><strong>${band(m.scenarios[1].ordersDayLow,m.scenarios[1].ordersDayHigh)}</strong><small>City scenario · no ward allocation</small></div></div>
 ${priorityNetworkResults()}
 ${panel('Location decision checks','Site suitability remains unverified',`<div class="table-scroll"><table><thead><tr><th>Local factor</th><th>Required check</th><th>Status</th></tr></thead><tbody>${riskRows(c)}</tbody></table></div>`)}
 `;
}
function locationBenefits(){
 const L=LOCATION_DATA,s=selectedSpatial(),p=L.population;
 const one=L.wards.map(w=>({id:w.id,hops:L.wards.reduce((v,d)=>v+d.population*L.distance[d.id-1][w.id-1],0)/p,near:L.wards.reduce((v,d)=>v+(L.distance[d.id-1][w.id-1]<=1?d.population:0),0)})).sort((a,b)=>a.hops-b.hops||b.near-a.near||a.id-b.id);
 const inspected=one.find(x=>x.id===spatialState.ward),average=one.reduce((v,x)=>v+x.hops,0)/one.length,first=L.scenarios[0];
 return panel('Location benefit comparison','Geographic model results · not customer reach or delivery time',`<div class="benefit-grid"><div><span>${spatialState.p===1?'Separation vs average single ward':'Separation vs one-area model'}</span><strong>${pct((1-s.weightedHops/(spatialState.p===1?average:first.weightedHops))*100)}</strong><small>Lower population-weighted ward transitions</small></div><div><span>Selected + adjacent population</span><strong>${number(s.oneHopPopulation)}</strong><small>${pct(s.withinOneHopPct)} of ${number(p)} baseline residents</small></div><div><span>Inspected Ward ${spatialState.ward} · single-area rank</span><strong>${one.indexOf(inspected)+1} / 38</strong><small>${number(inspected.hops,2)} weighted ward transitions</small></div></div><div class="table-scroll"><table><thead><tr><th>Best single search areas</th><th>Weighted transitions ↓</th><th>Selected + adjacent population</th><th>Built-up land · 2021</th></tr></thead><tbody>${one.slice(0,5).map(x=>`<tr class="${x.id===spatialState.ward?'base-row':''}"><td><button class="small-link" data-geo-ward="${x.id}">Ward ${x.id} · ${esc(L.wards[x.id-1].name)}</button></td><td>${number(x.hops,2)}</td><td>${number(x.near)}</td><td>${pct(geoWard(x.id).builtPct,0)}</td></tr>`).join('')}</tbody></table></div><div class="panel-foot">Built-up includes roads and industrial structures · Ward revenue and incremental customers not estimated</div>`);
}
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-map-city],[data-city-map-evidence]');if(!b)return;
 if(b.dataset.cityMapEvidence){geographicEvidence(b.dataset.cityMapEvidence);return;}
 if(!shortlist.some(c=>c.name===b.dataset.mapCity))return;
 mapState.cityName=b.dataset.mapCity;mapState.priorityWard=null;mapState.zoom=1;mapState.cx=800;mapState.cy=759.5;mapState.base='satellite';navigate('locations');
});

document.addEventListener('click',e=>{
 const b=e.target.closest('[data-priority-ward],[data-priority-focus]');if(!b)return;
 const id=Number(b.dataset.priorityWard||b.dataset.priorityFocus),g=PRIORITY_MAPS.cities.find(x=>x.name===mapState.cityName),w=CITY_WARDS[mapState.cityName]?.wards.find(x=>x.id===id);if(!g||!w)return;
 mapState.priorityWard=id;
 if(b.dataset.priorityFocus){const p=cityWardPoint(g,w.anchor);mapState.zoom=3;mapState.cx=p[0];mapState.cy=p[1];}
 render();
});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-priority-ward]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});

document.addEventListener('click',e=>{
 const b=e.target.closest('[data-network-p]');if(!b)return;const p=Number(b.dataset.networkP);if(![1,2,3,4].includes(p)||mapState.cityName==='Nagpur')return;
 mapState.networkP=p;mapState.priorityWard=priorityNetwork().areas[0];render();
});
