/* Read-only geographic research. Symbols are search-area references, never premises. */
'use strict';
const mapState={cityName:'Nagpur',base:'satellite',boundaries:true,competitors:false,zoom:1,cx:800,cy:759.5};
function geoWard(id){return SATELLITE_DATA.wards.find(w=>w.id===id);}
function mapViewBox(){const width=1600/mapState.zoom,height=1519/mapState.zoom;return [mapState.cx-width/2,mapState.cy-height/2,width,height].join(' ');}
function satelliteMap(){
 const D=SATELLITE_DATA,s=selectedSpatial(),chosen=new Set(s.sites),z=mapState.zoom;
 let out=`<svg id="satellite-map" viewBox="${mapViewBox()}" role="group" aria-label="Nagpur satellite atlas. Approximate ward overlay; pins identify search wards, not store buildings."><rect x="-1600" y="-1519" width="4800" height="4557" fill="#24372f"/><image href="${mapState.base==='landcover'?D.landcover:D.satellite}" x="0" y="0" width="1600" height="1519"/>`;
 if(mapState.base==='builtup')out+=`<image href="${D.builtup}" x="0" y="0" width="1600" height="1519"/>`;
 D.wards.forEach(g=>{
  const selected=chosen.has(g.id),inspected=spatialState.ward===g.id;
  out+=`<path d="M${g.polygon.map(p=>p.map(v=>v.toFixed(1)).join(',')).join('L')}Z" fill="${selected?'#efd76a35':'transparent'}" stroke="${selected?'#ffe998':inspected?'#ffffff':mapState.boundaries?'#fff8cbe6':'transparent'}" stroke-width="${(selected?4:inspected?3.4:2.1)/z}" tabindex="0" role="button" data-geo-ward="${g.id}" aria-label="Inspect ward ${g.id}"><title>Ward ${g.id} · approximate aligned boundary</title></path>`;
  if(mapState.boundaries&&!selected)out+=`<text class="geo-ward-label" x="${g.anchor[0]}" y="${g.anchor[1]}" font-size="${18/z}" stroke-width="${2/z}">${g.id}</text>`;
 });
 s.sites.forEach((id,i)=>{const g=geoWard(id);out+=`<g class="geo-pin" transform="translate(${g.anchor.join(',')}) scale(${1/z})" tabindex="0" role="button" data-geo-ward="${id}" aria-label="Recommended search area ${i+1}: ward ${id}"><path d="M0 21C-10 9-22-3-22-17a22 22 0 1144 0C22-3 10 9 0 21Z" fill="#f1d863" stroke="#24372f" stroke-width="2"/><text text-anchor="middle" y="-10" fill="#20362d" font-size="20" font-weight="700">${id}</text><rect x="-71" y="29" width="142" height="28" rx="3" fill="#162d24"/><text x="0" y="48" text-anchor="middle" font-size="13" fill="#fff">SEARCH AREA ${i+1}</text></g>`;});
 if(mapState.competitors){const g=geoWard(15);out+=`<g transform="translate(${g.anchor[0]-55},${g.anchor[1]-25}) scale(${1/z})" role="button" tabindex="0" data-map-action="competition" aria-label="Blinkit reported neighbourhood evidence, not a store location"><path d="M0-20L20 0 0 20-20 0Z" fill="#8cd8cf" stroke="#16392d" stroke-width="2"/><text y="6" text-anchor="middle" font-size="17" fill="#16392d" font-weight="700">B</text><rect x="-94" y="26" width="188" height="44" rx="3" fill="#162d24"/><text y="43" text-anchor="middle" font-size="12" fill="#b8f4eb">REPORTED NEIGHBOURHOODS</text><text y="59" text-anchor="middle" font-size="11" fill="#f4f7ee">Ward reference · not a store</text></g>`;}
 return out+'</svg>';
}
function competitorEvidence(){
 document.getElementById('method-title').textContent='Competition / geographic evidence';
 document.getElementById('method-body').innerHTML=`<div class="evidence-summary"><strong>Nagpur</strong><span>Store addresses and service polygons remain unverified.</span></div>
 <section class="method-section"><h3>Blinkit · named neighbourhoods</h3><p>Albinder Dhindsa’s launch announcement names Dharampeth, Gokulpeth and Ram Nagar. The map’s diamond uses a Ward 15 reference near these named areas. It is not the store address, a count of stores or a coverage boundary. The announcement is historical; the current FAQ separately lists Nagpur.</p><p><a href="https://www.linkedin.com/posts/adhindsa_blinkit-is-now-live-in-nagpur-we-opened-activity-7243144777775415296-7igu" target="_blank" rel="noopener">Company leader announcement ↗</a> · <a href="https://blinkit.com/faq" target="_blank" rel="noopener">Current city listing ↗</a> · <a href="https://nmcnagpur.gov.in/assets/300/2025/09/mediafiles/QGIS_MAP_15_merged.pdf" target="_blank" rel="noopener">Locality-name reference ↗</a></p></section>
 <section class="method-section"><h3>Swiggy Instamart · catalogue evidence</h3><p>An official Nagpur catalogue exists. Its displayed delivery time is not used as a citywide or address-specific promise. No physical-store address has been verified.</p><a href="https://www.swiggy.com/instamart/city/nagpur/b/grameen" target="_blank" rel="noopener">Official Nagpur catalogue ↗</a></section>
 <section class="method-section"><h3>Zepto · historical Nagpur establishment</h3><p>The official UDRHP-I describes a Nagpur establishment in a June 2025 record (PDF page 588). Two PDF extractions agree. No address or current operating status is established.</p><a href="https://cdn.zeptonow.com/investors/documents/Zepto%20Limited%20-%20UDRHP-I.pdf" target="_blank" rel="noopener">Official investor document ↗</a></section><section class="method-section"><h3>Flipkart Minutes · presence unresolved</h3><p>A complete official store roster for Nagpur was not established. Hiring posts and third-party store maps are leads, not verified operating stores. Entry and infill remain separate possibilities.</p></section>
 <section class="method-section"><h3>Jaipur · Minutes neighbourhood evidence</h3><p>The Flipkart Minutes brand account names Malviya Nagar, Vaishali Nagar and Pratap Nagar. This supports reported neighbourhood presence, without establishing building coordinates or current delivery polygons.</p><a href="https://www.linkedin.com/posts/flipkartminutes_flipkartminutes-flipkart-jaipur-activity-7419711035235823617-8uY0" target="_blank" rel="noopener">Company statement ↗</a></section>
 <section class="method-section"><h3>Coverage is not a circle</h3><p>Competitor pins require a verified operational address. Catchments require address-level service observations or an official polygon. Neither a nationwide delivery-speed average nor a store’s straight-line radius establishes ten-minute service. No customer or revenue gap is calculated from these incomplete records.</p></section>`;
 document.getElementById('method-dialog').showModal();
}
function satelliteMethod(){
 spatialMethod();document.getElementById('method-title').textContent='Satellite & location model';
 const D=SATELLITE_DATA;
 document.getElementById('method-body').innerHTML=`<section class="method-section"><h3>Satellite evidence / 2021</h3><p>The map uses ESA WorldCover’s annual Sentinel-2 composite. The built-up overlay and percentages use raw WorldCover v200 class 50, which includes buildings, roads and industrial structures. This is not a residential footprint, current population, household income, rent estimate or a model trained on Flipkart orders.</p><p>Municipal boundaries were digitised from the final 2025 ward map and approximately registered to the satellite raster using shared water features. Position accuracy is unvalidated. Pins remain administrative search references, not buildings or addresses. Boundaries and pixels have different dates.</p><p>Built-up percentages were computed twice using separate rasterisation methods; the largest discrepancy is ${number(Math.max(...D.verification.wardChecks.map(x=>x.differencePctPoints)),2)} percentage points. This checks calculations, not ground truth. The displayed sensitivity shifts each polygon 150 metres in four directions; it is an analyst stress test, not a confidence interval. Built-up percentages do not change the active p-median ranking.</p>${D.sources.map(s=>`<div class="source-row"><a href="${s.url}" target="_blank" rel="noopener">${esc(s.title)} ↗</a></div>`).join('')}</section>`+document.getElementById('method-body').innerHTML;
}
function atlasLocations(){
 if(mapState.cityName!=='Nagpur')return priorityCityMap();
 const L=LOCATION_DATA,D=SATELLITE_DATA,s=selectedSpatial(),w=L.wards[spatialState.ward-1],g=geoWard(w.id),c=T.cities.find(c=>c.name==='Nagpur');
 return `<div class="atlas-heading map-room-heading"><div><span class="overline">LOCATION INTELLIGENCE / NAGPUR</span><h1>Nagpur store locations</h1></div><button class="quiet-button" data-map-action="method">Model details ↗</button></div>
 ${mapCityTabs()}<div class="map-room-command"><div class="map-room-network"><span class="control-label">SEARCH NETWORK</span><div class="segments">${[1,2,3,4].map(p=>`<button data-spatial-p="${p}" class="${spatialState.p===p?'active':''}" aria-pressed="${spatialState.p===p}">${p} ${p===1?'area':'areas'}</button>`).join('')}</div></div><div class="map-room-signal"><span class="signal-dot"></span><span>Conditional pilot <b>1 store</b></span></div><button class="quiet-button" data-city="${c.id}">Business case ↗</button></div>
 <div class="map-room"><section class="geo-surface"><div class="geo-top"><div class="geo-tabs" aria-label="Base map">${[['satellite','Satellite'],['builtup','Built-up'],['landcover','Land cover']].map(([key,name])=>`<button data-map-base="${key}" aria-pressed="${mapState.base===key}" class="${mapState.base===key?'active':''}">${name}</button>`).join('')}</div><span>ESA / 2021</span></div><div class="geo-canvas">${satelliteMap()}<div class="geo-controls"><button data-map-action="in" aria-label="Zoom in">+</button><button data-map-action="out" aria-label="Zoom out">−</button><button data-map-action="fit" aria-label="Fit whole city">⌂</button><button data-map-action="focus" aria-label="Focus inspected ward">⌖</button></div><div class="geo-pan"><button data-map-action="north" aria-label="Pan north">↑</button><button data-map-action="west" aria-label="Pan west">←</button><button data-map-action="east" aria-label="Pan east">→</button><button data-map-action="south" aria-label="Pan south">↓</button></div><div class="geo-corner"><b>N ↑</b><span>Approximate ward alignment<br>Search pins ≠ store premises</span></div></div><div class="geo-layer-bar"><button data-map-action="wards" aria-pressed="${mapState.boundaries}" class="${mapState.boundaries?'on':''}"><i></i>Ward boundaries</button><button data-map-action="rivals" aria-pressed="${mapState.competitors}" class="${mapState.competitors?'on':''}"><i></i>Competitor evidence</button><span>${mapState.base==='builtup'?'Gold: built-up classification':mapState.base==='landcover'?'Gold: built-up · blue: water · green: trees':'Annual composite · not live imagery'}</span></div><div class="geo-attribution">© ESA WorldCover project 2021 / Contains modified Copernicus Sentinel data (2021) processed by ESA WorldCover consortium · <a href="https://esa-worldcover.org/en/data-access" target="_blank" rel="noopener">CC BY 4.0</a></div></section>
 <aside class="geo-dossier"><div class="geo-dossier-heading"><span class="overline">${spatialState.p===1?'FIRST SEARCH PRIORITY':'NETWORK SCENARIO'}</span><h2>${spatialState.p===1?'Start in Ward '+s.sites[0]:s.sites.length+' search areas'}</h2><span class="small-status">Premises not selected</span></div><div class="geo-site-list">${s.sites.map((id,i)=>`<button data-geo-ward="${id}" class="${id===w.id?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(L.wards[id-1].name)}</b><small>Ward ${id}</small></div><i>↗</i></button>`).join('')}</div><div class="geo-inspector"><div class="overline">INSPECTING WARD ${w.id}</div><h3>${esc(w.name)}</h3><div class="geo-stat-pair"><div><strong>${number(w.population)}</strong><span>delimitation population</span></div><div><strong>${number(g.builtPct,0)}%</strong><span>built-up land · 2021</span></div></div><div class="built-meter"><i style="width:${g.builtPct}%"></i></div><div class="geo-footnote">${number(g.builtSensitivity[0],0)}–${number(g.builtSensitivity[1],0)}% under alignment stress</div><details><summary>Area profile &amp; access</summary><p>${esc(w.localities)}</p><p>${esc(w.gate)}</p><p>Built-up includes roads and industrial buildings. Local income and occupied household density are unmeasured.</p></details></div><div class="geo-competition"><div class="overline">NAGPUR / COMPETITION</div><div><span class="brand-square blink">b</span><b>Blinkit</b><small>City + neighbourhoods</small></div><div><span class="brand-square insta">i</span><b>Instamart</b><small>Catalogue only</small></div><div><span class="brand-square zepto">z</span><b>Zepto</b><small>Historical establishment</small></div><div><span class="brand-square flip">m</span><b>Minutes</b><small>Unconfirmed</small></div><button data-map-action="competition">Review location evidence <span>↗</span></button></div></aside></div>
 ${locationBenefits()}
 <div class="geo-readouts"><section><span class="overline">DELIVERY FEASIBILITY</span><h2>Delivery feasibility</h2><div class="time-equation"><b>Pick</b><span>+</span><b>Dispatch</b><span>+</span><b>Road time</b><span>+</span><b>Doorstep</b><span>≤</span><strong>10 min</strong></div><p>Peak road time: unmeasured · Ten-minute coverage: unvalidated</p><details><summary>Why there is no coverage radius</summary><p>Blinkit’s official sources describe a two-minute pick-and-pack benchmark, leaving at most eight minutes for all other stages under a ten-minute target. This is a competitor benchmark, not Flipkart’s operating performance. Its older company blog and current FAQ report different fleet-speed averages; neither is a Nagpur traffic measurement. No radius or service polygon is inferred.</p><p><a href="https://blinkit.com/faq" target="_blank" rel="noopener">Company FAQ ↗</a> · <a href="https://blinkit.com/blog/7-years-search-product-market-fit/" target="_blank" rel="noopener">Company operating explanation ↗</a></p></details></section><section><span class="overline">NEXT INVESTMENT DECISION</span><h2>Commercial decision</h2><div class="compact-case"><span>10% city GMV ambition</span><strong>${cr(c.model.entryBase,1)}</strong></div><div class="compact-case"><span>Physical store locations verified</span><strong>Not established</strong></div><div class="compact-case"><span>Current local competitor share</span><strong>Not disclosed</strong></div><button class="full-link" id="export-geography">Download geographic analysis <span>↓</span></button></section></div>
 <details class="location-scope algorithm-details"><summary>Compare the location-allocation algorithms</summary><div class="algorithm-content"><div class="segments">${[['median','Population proximity'],['coverage','Adjacent population']].map(([key,name])=>`<button data-spatial-mode="${key}" class="${spatialState.mode===key?'active':''}" aria-pressed="${spatialState.mode===key}">${name}</button>`).join('')}</div>${networkChart()}<p>Every combination of one to four wards is evaluated. The objective uses shared-boundary transitions. Satellite measures describe the areas; they do not substitute for road-network travel times or determine store count.</p><button class="quiet-button" data-map-action="method">Full methodology ↗</button></div></details>
`;
}
document.addEventListener('click',e=>{
 const el=e.target.closest('[data-map-base],[data-map-action],[data-geo-ward],#export-geography');if(!el)return;
 if(el.dataset.geoWard){spatialState.ward=Number(el.dataset.geoWard);render();return;}
 if(el.dataset.mapBase){mapState.base=el.dataset.mapBase;render();return;}
 if(el.id==='export-geography'){const {satellite,landcover,builtup,...analysis}=SATELLITE_DATA;download('Minutes-Nagpur-geographic-analysis.json',JSON.stringify({wardModel:LOCATION_DATA,satelliteAnalysis:analysis},null,2),'application/json');toast('Geographic model exported.');return;}
 const action=el.dataset.mapAction;
 if(action==='competition'){competitorEvidence();return;}if(action==='method'){satelliteMethod();return;}
 if(action==='in')mapState.zoom=Math.min(4,mapState.zoom*1.5);
 if(action==='out')mapState.zoom=Math.max(1,mapState.zoom/1.5);
 if(action==='fit'){mapState.zoom=1;mapState.cx=800;mapState.cy=759.5;}
 if(action==='focus'){const g=geoWard(spatialState.ward);mapState.zoom=3;mapState.cx=g.anchor[0];mapState.cy=g.anchor[1];}
 if(action==='wards')mapState.boundaries=!mapState.boundaries;
 if(action==='rivals')mapState.competitors=!mapState.competitors;
 if(action==='north')mapState.cy-=200/mapState.zoom;if(action==='south')mapState.cy+=200/mapState.zoom;
 if(action==='east')mapState.cx+=200/mapState.zoom;if(action==='west')mapState.cx-=200/mapState.zoom;
 mapState.cx=Math.max(0,Math.min(1600,mapState.cx));mapState.cy=Math.max(0,Math.min(1519,mapState.cy));render();
});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('svg [data-geo-ward],svg [data-map-action]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
