/* Read-only expansion terminal. All model values are precomputed and versioned. */
'use strict';
const T=TERMINAL_DATA, B=MINUTES_DATA;
const byId=new Map(T.cities.map(c=>[c.id,c]));
const ranked=T.ranked.map(id=>byId.get(id));
const shortlist=T.shortlist.map(id=>byId.get(id));
const metrics=Object.fromEntries(T.benchmarks.metrics.map(x=>[x.id,x]));
const main=document.getElementById('main');
const state={view:'overview',city:shortlist[0]?.id||ranked[0].id,filter:'priority',region:'all',sort:'score',page:0};
const esc=x=>String(x??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const number=(n,d=0)=>Number.isFinite(n)?n.toLocaleString('en-IN',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const cr=(n,d=0)=>Number.isFinite(n)?'₹'+number(n,d)+' cr':'—';
const lakh=n=>Number.isFinite(n)?number(n/1e5,1)+' lakh':'—';
const pct=(n,d=1)=>Number.isFinite(n)?number(n,d)+'%':'—';
const band=(l,h,d=0,prefix='')=>Number.isFinite(l)&&Number.isFinite(h)?prefix+number(l,d)+'–'+number(h,d):'—';
const moneyBand=(l,h)=>band(l,h,0,'₹')+' cr';
const badge=(text,kind='')=>`<span class="badge ${kind}">${esc(text)}</span>`;
const cityButton=(c,label)=>`<button class="city-name" data-city="${c.id}">${esc(label||c.name)}</button>`;
const metric=(label,value,sub)=>`<div class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div><div class="kpi-sub">${sub}</div></div>`;
const presenceLabel=c=>c.observedPresence?'Presence documented':'Status unconfirmed';
const presenceBadge=c=>badge(presenceLabel(c),c.observedPresence?'green':'amber');
const score=c=>c.model?.score==null?'—':number(c.model.score,1);
const modelNote='2026 planning estimate · not reported city sales';
const peerNote='Planning equivalents use an assumed ₹508–691 transaction value and 1,089 orders/store-day. Valuation sensitivity, not a verified GMV conversion, capacity limit or breakeven.';

function scoreCell(c){return c.model?.score==null?'<span class="muted">Incomplete</span>':`<span class="score-cell">${score(c)}<span class="tiny-bar"><i style="width:${c.model.score}%"></i></span></span>`;}
function panel(title,subtitle,body,extra='',foot=''){return `<section class="panel"><div class="panel-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div>${extra}</div>${body}${foot?`<div class="panel-foot">${foot}</div>`:''}</section>`;}
function head(title,sub,extra=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`;}
function sourceLink(id){const s=T.sources.find(x=>x.id===id);return s?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||id)}</a>`:esc(id);}

function legacyOverview(){
 const sum=shortlist.reduce((v,c)=>v+c.model.marketBase,0), lead=shortlist[0];
 const rows=shortlist.map((c,i)=>`<tr data-city="${c.id}"><td class="rank">${String(i+1).padStart(2,'0')}</td><td>${cityButton(c)}<div class="subcell">${esc(c.state)}</div></td><td>${scoreCell(c)}</td><td class="num nowrap">${cr(c.model.marketBase)}</td><td class="num">${band(c.model.storeLow,c.model.storeHigh,1)}</td><td><span aria-hidden="true">↗</span></td></tr>`).join('');
 return head('The next market, with a stronger case.','City screening, commercial potential and a disciplined path to entry.',badge('2026 planning case'))+
 `<section class="hero"><div><span class="eyebrow">RECOMMENDED DILIGENCE SEQUENCE</span><h2>Validate ${esc(lead.name)} first.<br>Keep expansion selective.</h2><p>The strongest screening score among markets with no documented Minutes presence. Confirm footprint before treating any recommendation as new-city entry.</p><div class="hero-chips">${shortlist.slice(0,3).map((c,i)=>`<button data-city="${c.id}">${String(i+1).padStart(2,'0')} &nbsp; ${esc(c.name)} &nbsp; ↗</button>`).join('')}</div></div><div class="hero-stats"><div><div class="big accent">${cr(sum)}</div><div class="label">Combined city GMV · modelled, annual</div></div><div><div class="big">${cr(sum*.1)}</div><div class="label">At a 10% entrant ambition</div></div><div><div class="big">${shortlist.length} markets</div><div class="label">Commercially screened diligence list</div></div><div><div class="big">1 → scale</div><div class="label">Conditional pilot sequence per city</div></div></div></section>`+
 `<div class="kpi-strip">${metric('Urban markets screened',number(T.stats.markets),'Census Class I & II · 2011 geography')}${metric('Minutes presence documented',number(T.stats.presenceMarkets),'Named matches · not the complete footprint')}${metric('Candidates with a complete score',number(T.stats.rankedCandidates),'Presence unconfirmed · conditional screening')}${metric('Nonmetro industry pool, 2025',cr(T.stats.nonmetroPoolCr),'Published industry estimate · all operators')}</div>`+
 `<div class="split">${panel('Commercial priority list','One-store hurdle applied before sequencing',`<div class="table-scroll"><table class="compact-table"><thead><tr><th>#</th><th>Market</th><th>Score /100</th><th>City GMV /yr</th><th>Store eq.</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`,`<button class="small-link" data-view="markets">View all markets ↗</button>`,'2026 planning case; store equivalents at 10% ambition. Every city above has unconfirmed Minutes status.')}
 ${panel('Market in focus','Read the commercial case',`<div class="feature-city">${presenceBadge(lead)}<div class="city-big">${esc(lead.name)}</div><p>${esc(shortThesis(lead))}</p><div class="feature-values"><div><b>${moneyBand(lead.model.marketLow,lead.model.marketHigh)}</b><span>Annual city GMV · model range</span></div><div><b>${band(lead.model.oneStoreShareLow,lead.model.oneStoreShareHigh,1)}%</b><span>Share ambition for one store equivalent</span></div></div><button class="primary-button" data-city="${lead.id}">Open city intelligence <span>↗</span></button></div>`)}</div>`+
 `<div class="bottom-grid">${panel('Opportunity versus concentration','Diligence candidates · modelled GMV and historical density',`<div class="panel-body">${scatter(shortlist)}<div class="chart-caption"><span>← Lower density · 2011 persons /km² · Higher density →</span><span>Size = city GMV</span></div></div>`)}
 ${panel('Three decisions that matter','A city ranking is the start of the investment case',`<div class="panel-body"><div class="insight-row"><span class="insight-number">01</span><div><h3>Separate entry from infill.</h3><p>Minutes reports 150+ cities. The public named list is incomplete; an unmentioned city is not confirmed absent.</p></div></div><div class="insight-row"><span class="insight-number">02</span><div><h3>Size the prize before counting stores.</h3><p>Compare a modest foothold, a 10% ambition and a stretch case. Expand only after the demand hurdle is credible.</p></div></div><div class="insight-row"><span class="insight-number">03</span><div><h3>Compete on the customer mission.</h3><p>Local assortment and dependable replenishment need a separate operating case. National shares cannot locate a city-level gap.</p></div></div></div>`)}</div>`;
}

function scatter(list){
 const vals=list.filter(c=>c.density),maxD=Math.max(...vals.map(c=>c.density))*1.3,maxM=Math.max(...vals.map(c=>c.model.marketBase))*1.22;
 const x=v=>62+v/maxD*510,y=v=>218-v/maxM*175;
 let svg=`<svg class="chart-svg" viewBox="0 0 630 257" role="img" aria-label="Comparison of city GMV estimates and historical urban density"><text x="9" y="17">GMV ₹ cr</text>`;
 for(let i=0;i<=3;i++){const v=maxM*i/3;svg+=`<line x1="60" y1="${y(v)}" x2="605" y2="${y(v)}" class="gridline"/><text x="48" y="${y(v)+4}" text-anchor="end">${number(v)}</text>`;}
 for(let i=0;i<=3;i++){const v=maxD*i/3;svg+=`<text x="${x(v)}" y="242" text-anchor="middle">${number(v)}</text>`;}
 vals.forEach((c,i)=>{const cx=x(c.density),cy=y(c.model.marketBase),r=7+Math.sqrt(c.model.marketBase/maxM)*10;svg+=`<g><title>${esc(c.name)}: ${cr(c.model.marketBase)}; ${number(c.density)} persons/km² (2011)</title><circle cx="${cx}" cy="${cy}" r="${r}" fill="${i===0?'#2855d9':'#81a0de'}" fill-opacity=".77" stroke="white" stroke-width="2"/><text x="${cx+19}" y="${cy+(i%2?15:-11)}" class="chart-label">${esc(c.name.length>17?c.name.slice(0,15)+'…':c.name)}</text></g>`;});return svg+'</svg>';
}

function filteredCities(){
 let list=T.cities.filter(c=>state.region==='all'||c.state===state.region);
 if(state.filter==='priority')list=list.filter(c=>T.shortlist.includes(c.id));
 if(state.filter==='candidates')list=list.filter(c=>!c.observedPresence&&!c.metro);
 if(state.filter==='existing')list=list.filter(c=>c.observedPresence);
 list.sort((a,b)=>state.sort==='name'?a.name.localeCompare(b.name):state.sort==='gmv'?((b.model?.marketBase??-1)-(a.model?.marketBase??-1)):state.sort==='population'?b.pop-a.pop:((b.model?.score??-1)-(a.model?.score??-1))||a.name.localeCompare(b.name));
 return list;
}
function competitorNames(c){
 const names=[...new Set(c.competitors.map(e=>e.platform+(e.status.includes('catalogue')?' (catalogue)':'')))];
 for(const e of LOCAL_COMPETITION[c.name]||[]){if(!names.some(n=>n.toLowerCase().includes(e.brand.toLowerCase())))names.push(e.brand+(e.status.includes('Catalogue')?' (catalogue)':' (historical)'));}
 return names.length?names.map(esc).join('<br>'):'No affirmative record';
}

function riskRows(c){
 const risks={Nagpur:[['Railway crossings','Peak cross-city routes'],['Ganeshpeth / Rambagh','Bus, hospital and loading access'],['38-ward model','Ward 17 first search area']],Vadodara:[['Vishwamitri river','Bridge access and flood exposure'],['Municipal flood plan','Parcel elevation and wet-season access']],Visakhapatnam:[['Coastal exposure','Cyclone and flood resilience'],['Ramnagar','Verify current Blinkit service extent']],Kochi:[['Waterways / bridges','Separate road catchments'],['Kaloor','Verify current Blinkit service extent']],Thiruvananthapuram:[['Technopark phases','Existing occupancy vs future projects'],['Dispersed urban area','Local route validation']],Thrissur:[['Central road network','Event-day access and loading'],['Temple-centred core','Normal-day vs event demand']]};
 return (risks[c.name]||[['Current catchments','Road travel and occupied households']]).map(([a,b])=>`<tr><td>${esc(a)}</td><td>${esc(b)}</td><td>${badge('Check required','amber')}</td></tr>`).join('');
}

function decisionRows(c){
 const m=c.model,base=m?.scenarios[1];
 return [['Entry status',presenceLabel(c),c.observedPresence?'Assess infill':'Confirm entry vs infill'],['Initial store decision',c.observedPresence?'Existing market':c.pilot?'1-store pilot case':'Demand case first','Site economics unverified'],['Daily orders at 10% share',base?band(base.ordersDayLow,base.ordersDayHigh):'—','Model sensitivity'],['Peer orders /store /day','1,089','Benchmark, not breakeven'],['Current rent / contribution','Not established','No ROI calculated'],['Ten-minute delivery','Not validated','Peak routes + dispatch required'],['Competitor share / unserved gap','Not established','No city-level sales split']].map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td class="muted">${r[2]}</td></tr>`).join('');
}

function markets(){
 const list=filteredCities(),size=20,pages=Math.max(1,Math.ceil(list.length/size));state.page=Math.min(state.page,pages-1);
 const display=list.slice(state.page*size,(state.page+1)*size),opts=[...new Set(T.cities.map(c=>c.state))].sort();
 const rows=display.map(c=>`<tr><td class="frozen-city">${cityButton(c)}<div class="subcell">${esc(c.state)} · ${c.geotype}</div><div class="subcell">${presenceLabel(c)}</div></td><td>${scoreCell(c)}<div class="subcell">${c.model?.rank?'Rank '+c.model.rank:'Unranked'}</div></td><td class="num">${lakh(c.pop)}</td><td class="num">${lakh(c.populationProxy)}</td><td class="num">${number(c.households)}</td><td class="num">${number(c.area,1)}</td><td class="num">${number(c.density)}</td><td class="num">₹${number(c.coreMpce)}</td><td class="num">${pct(c.digitalPct)}</td><td class="num">${pct(c.otherWorkerPct)}</td><td class="num">${c.model?cr(c.model.marketBase,1):'Outside model'}</td><td class="num">${c.model?band(c.model.scenarios[1].ordersDayLow,c.model.scenarios[1].ordersDayHigh):'—'}</td><td class="num">${c.model?band(c.model.storeLow,c.model.storeHigh,2):'—'}</td><td class="num">${c.model?band(c.model.oneStoreShareLow,c.model.oneStoreShareHigh,1)+'%':'—'}</td><td>${competitorNames(c)}</td></tr>`).join('');
 return head('Market comparison','City inputs and modelled commercial potential',`<span class="badge">${number(list.length)} markets</span>`)+
 `<div class="toolbar"><div class="segments" aria-label="Market view">${[['priority','Priority list'],['candidates','Unconfirmed'],['existing','Minutes present'],['all','All markets']].map(([v,label])=>`<button data-filter="${v}" class="${state.filter===v?'active':''}" aria-pressed="${state.filter===v}">${label}</button>`).join('')}</div><div class="filters"><select id="state-filter" aria-label="Filter by Census state"><option value="all">All Census states</option>${opts.map(s=>`<option ${state.region===s?'selected':''} value="${esc(s)}">${esc(s)}</option>`).join('')}</select><select id="sort-filter" aria-label="Sort markets">${[['score','Attractiveness score'],['gmv','Market size'],['population','2011 population'],['name','City A–Z']].map(([v,t])=>`<option value="${v}" ${state.sort===v?'selected':''}>${t}</option>`).join('')}</select></div></div>`+
 `<section class="panel parameter-panel"><div class="parameter-guide"><span><i class="key-dot"></i>Observed city inputs · 2011</span><span><i class="key-dot proxy"></i>State-based proxies</span><span><i class="key-dot model"></i>2026 model</span><b>Scroll horizontally for all parameters →</b></div><div class="table-scroll" tabindex="0" role="region" aria-label="City parameter comparison"><table class="parameter-table"><thead><tr class="group-head"><th rowspan="2" class="frozen-city">City</th><th rowspan="2">Score /100</th><th>Observed</th><th>Proxy</th><th colspan="3">Observed · Census 2011</th><th colspan="2">State urban proxies</th><th>Observed</th><th colspan="4">Commercial model · 2026</th><th rowspan="2">Rival evidence</th></tr><tr><th>Population<br><small>2011</small></th><th>Population<br><small>2025</small></th><th>Households</th><th>Area<br><small>km²</small></th><th>Density<br><small>people /km²</small></th><th>Core spending<br><small>₹ /person /30d · 2023–24</small></th><th>Online-food HH<br><small>% · 2025 proxy</small></th><th>Other workers<br><small>% of people · 2011</small></th><th>City GMV<br><small>₹ cr /year</small></th><th>Orders /day<br><small>10% share scenario</small></th><th>Store equivalents<br><small>10% share scenario</small></th><th>Share for 1 store<br><small>peer throughput</small></th></tr></thead><tbody>${rows||'<tr><td colspan="15" class="empty">No markets in this view. Choose another state or category.</td></tr>'}</tbody></table></div><div class="pagination"><span>${list.length?number(state.page*size+1)+'–'+number(Math.min((state.page+1)*size,list.length)):'0'} of ${number(list.length)} markets</span><div><button id="prev-page" ${state.page===0?'disabled':''}>← Previous</button><button id="next-page" ${state.page>=pages-1?'disabled':''}>Next →</button></div></div><div class="panel-foot">Unconfirmed ≠ absent · State spending ≠ city income · Store equivalents ≠ required physical stores</div></section>`;
}

function shortThesis(c){
 if(c.case)return c.case.strategicThesis;
 if(c.observedPresence)return 'Treat the city as an infill opportunity. Add stores only for incremental reach or service improvement after existing coverage is reconciled.';
 if(c.density>=8000)return 'A concentrated historical settlement pattern supports a compact operating hypothesis. Earn repeat household demand before spreading the network across the city.';
 return 'The broad urban market contains several possible demand clusters. Start with a bounded operating case; citywide population is not a ten-minute catchment.';
}
function strategy(c){
 const k=c.case;
 const steps=k?[
  ['Customer mission',k.strategicThesis],['Entry approach',k.recommendedCityStrategy.replaceAll('�','–')],['Earn the next store',k.scaleTrigger]
 ]:c.observedPresence?[
  ['Measure incremental demand','Prioritise gaps outside existing service areas and unmet missions inside them. Existing city demand is not all available to a new store.'],['Improve the network','Use additional stores to add unique customers or reduce route friction. Avoid shifting the same orders between nearby stores.'],['Earn further investment','Require incremental contribution and dependable peak service before expanding the footprint.']
 ]:[
  ['Lead with repeat essentials',c.digitalPct>=24.5856?'State online-food participation supports testing digitally familiar households. Build frequency through dependable replenishment and locally relevant essentials.':'Start with routine household top-ups. State online-food participation is below the national proxy; do not build the launch around immediate mass adoption.'],
  ['Keep the first catchment bounded',c.pilot?'The base ambition clears one benchmark-equivalent store at the lower basket assumption. Advance a one-store pilot business case after footprint and operating checks.':'The base ambition falls below one benchmark-equivalent store. Test adoption and willingness to repeat before committing a dedicated network.'],
  ['Expand on incremental orders',c.density>=8000?'Historical density favours testing compact coverage, but peak travel, loading and access still govern the real network.':'Broad UA density suggests testing separate demand clusters. Avoid attributing far-flung households to one store or adding an arbitrary geographic multiplier.']
 ];
 const tags=k?[k.operatingBand==='C'?'Resilience gate':'Operating case available','Current rent unverified','Peak routes unverified']:['Historic geography','Current rent unverified','Peak routes unverified'];
 return `<div class="strategy-grid">${steps.map(([t,b],i)=>`<div class="strategy-step"><div class="step">0${i+1}</div><h3>${esc(t)}</h3><p>${esc(b)}</p></div>`).join('')}</div>${k?`<div class="notice">${esc(k.transportAndResilience)}</div>`:''}<div class="risk-tags">${tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`;
}
function competitors(c){
 const players=[['Blinkit','blinkit','b'],['Swiggy Instamart','instamart','i'],['Zepto','zepto','z']];
 return players.map(([name,cl,letter])=>{
  const records=c.competitors.filter(e=>e.platform.toLowerCase().includes(name==='Swiggy Instamart'?'instamart':name.toLowerCase()));
  const confirmed=records.some(e=>!e.status.includes('catalogue')&&!e.status.includes('unknown'));
  const local=(LOCAL_COMPETITION[c.name]||[]).filter(e=>e.brand.toLowerCase().includes(name==='Swiggy Instamart'?'instamart':name.toLowerCase()));
  const catalogue=records.some(e=>e.status.includes('catalogue'))||local.some(e=>e.status.includes('Catalogue'));
  const historical=local.length>0&&!catalogue;
  return `<div class="competitor-row"><div class="competitor-brand"><span class="logo-dot ${cl}">${letter}</span>${name}</div><div class="right-text">${badge(confirmed?'City listed':catalogue?'Catalogue only':historical?'Historical record':'Unconfirmed',confirmed?'green':'gray')}<small>City share: not disclosed</small></div></div>`;
 }).join('')+`<div class="section-note">City shares and unserved demand not established. Catalogue evidence does not confirm delivery.</div>`;
}
function city(){
 const c=byId.get(state.city)||shortlist[0],m=c.model,hasMap=shortlist.some(x=>x.id===c.id);
 const top=`<div class="city-top"><div><span class="eyebrow">CITY INTELLIGENCE / ${esc(c.state)}</span><h1>${esc(c.name)}</h1><p>${c.geotype==='UA'?'Urban agglomeration':'Town'} · 2011 geography${c.pooled?' · pooled successor-state proxies':''}</p></div><div>${presenceBadge(c)}<button class="quiet-button" data-city-method="${c.id}">Calculation details ↗</button></div></div><div class="city-pills">${shortlist.map(x=>`<button data-city="${x.id}" class="${c.id===x.id?'active':''}">${esc(x.name)}</button>`).join('')}<button data-view="markets">All markets ↗</button>${hasMap?`<button data-map-city="${esc(c.name)}">Open city map ↗</button>`:''}</div>`;
 if(!m)return top+panel('City fundamentals','Metro excluded from this market-sizing model',`<div class="panel-body">${fundamentalLines(c)}${competitors(c)}</div>`);
 const base=m.scenarios[1];
 const scoreHtml=m.complete?`<div class="score-header"><div class="score-ring" style="--score:${m.score}"><b>${number(m.score,1)}</b></div><div><h3>Attractiveness /100</h3><p>${m.rank?'Rank '+m.rank+' / '+T.stats.rankedCandidates:'Comparison score'}</p><p>${m.rankRange?'Rank range '+m.rankRange.join('–')+' under alternative weights':'Relative score, not success probability'}</p></div></div>${['Spending scale','City density','Online-food proxy','Other-worker share'].map((label,i)=>`<div class="pillar"><span>${label} · ${T.model.weights[i]*100}% weight</span><div class="pillar-track"><i style="width:${m.components[i]}%"></i></div><b>${number(m.components[i])}</b></div>`).join('')}`:`<div class="notice">Incomplete score: comparable city inputs missing.</div>`;
 const scenarios=`<div class="table-scroll"><table class="scenario-table"><thead><tr><th>Share scenario</th><th>GMV /yr</th><th>Orders /day</th><th>Store eq.</th></tr></thead><tbody>${m.scenarios.map((s,i)=>`<tr class="${i===1?'base-row':''}"><td>${pct(s.share*100,0)} ${i===1?badge('Base'):''}</td><td>${cr(s.gmvCr,1)}</td><td>${band(s.ordersDayLow,s.ordersDayHigh)}</td><td>${band(s.storeEquivLow,s.storeEquivHigh,2)}</td></tr>`).join('')}</tbody></table></div><div class="panel-foot">Share scenarios are assumptions, not unserved demand. ₹508–691/order; 1,089 orders/store-day.</div>`;
 return top+`<div class="kpi-strip">${metric('City GMV /year',cr(m.marketBase,1),'2026 central estimate')}${metric('GMV sensitivity',moneyBand(m.marketLow,m.marketHigh),'Growth + allocation scenarios')}${metric('Orders /day at 10% share',band(base.ordersDayLow,base.ordersDayHigh),'Transaction-value sensitivity')}${metric('Share for one store equivalent',band(m.oneStoreShareLow,m.oneStoreShareHigh,1)+'%','At national peer throughput')}</div>`+
 `<div class="analysis-grid">${panel('Market share scenarios','2026 city model',scenarios)}${panel('Attractiveness score','Percentile components · higher is better',`<div class="panel-body">${scoreHtml}</div>`)}</div>`+
 `<div class="analysis-grid">${panel('Demand and spending','City observations and state proxies',`<div class="panel-body">${fundamentalLines(c)}<div class="metric-line"><span>Annual core consumption envelope<small>2025 population proxy · 2023–24 prices</small></span><b>${cr(c.consumptionCr)}</b></div></div>`)}${panel('Competitive context','Official-source records · city level',`<div class="panel-body">${competitors(c)}${localCompetition(c.name)}</div>`)}</div>`+
 `<div class="analysis-grid">${panel('Store-count thresholds','Required city share at peer throughput',`<div class="table-scroll"><table><thead><tr><th>Store equivalents</th><th>Orders /day</th><th>Required share</th></tr></thead><tbody>${[1,2,3].map(n=>`<tr><td>${n}</td><td>${number(n*1089)}</td><td>${band(m.oneStoreShareLow*n,m.oneStoreShareHigh*n,1)}%</td></tr>`).join('')}</tbody></table></div><div class="panel-foot">Throughput sensitivity only · no route, capacity or breakeven validation</div>`)}${panel('Revenue sensitivity','10% share scenario',`<div class="panel-body"><div class="metric-line"><span>Consumer GMV /year</span><b>${cr(m.entryBase,1)}</b></div><div class="metric-line"><span>Peer revenue equivalent /year</span><b>${moneyBand(base.revenueEquivalentLowCr,base.revenueEquivalentHighCr)}</b></div><div class="metric-line"><span>Profit / ROI</span><b>Not established</b></div><div class="section-note">₹108/order peer monetisation benchmark; not Flipkart revenue.</div></div>`)}</div>`+
 panel('Entry decision','Commercial and operating status',`<div class="table-scroll"><table class="decision-table"><thead><tr><th>Decision input</th><th>Result</th><th>Status</th></tr></thead><tbody>${decisionRows(c)}</tbody></table></div>`)+
 panel('City-specific operating checks','Not included in the numeric score',`<div class="table-scroll"><table><thead><tr><th>Location factor</th><th>Required check</th><th>Status</th></tr></thead><tbody>${riskRows(c)}</tbody></table></div>`,hasMap?`<button class="small-link" data-map-city="${esc(c.name)}">City map ↗</button>`:'');
}

function fundamentalLines(c){const rows=[['Population',lakh(c.pop),'Observed · Census 2011'],['Population proxy',lakh(c.populationProxy),'2025 · state growth downscaled'],['Households',lakh(c.households),'Observed · Census 2011'],['Urban area',number(c.area,1)+' km²','Observed · Census 2011'],['Density',number(c.density)+' /km²','Historical broad city / UA'],['Core category spending','₹'+number(c.coreMpce),'State urban · per person /30 days'],['Online-food household proxy',pct(c.digitalPct),'State urban · CMS 2025'],['Main other-worker share',pct(c.otherWorkerPct),'Census 2011 · not formal employment']];return rows.map(([l,v,s])=>`<div class="metric-line"><span>${l}<small>${s}</small></span><b>${v}</b></div>`).join('');}

function brief(){
 const sum=shortlist.reduce((v,c)=>v+c.model.marketBase,0),lead=shortlist[0];
 return head('Expansion recommendations','Six-city comparison · 2026 planning scenarios',`<button class="export-button" id="print-brief">Print brief ↓</button>`)+
 `<div class="brief-summary"><div><span class="overline">FIRST COMMERCIAL REVIEW</span><h2>${esc(lead.name)}</h2><span>Score ${score(lead)} /100 · rank ${lead.model.rankRange.join('–')} in weight sensitivity</span></div><div><span>Combined city GMV /year</span><strong>${cr(sum)}</strong><small>Model estimate · all operators</small></div><div><span>Initial decision</span><strong>1 pilot case</strong><small>Nagpur · entry status and economics unresolved</small></div></div>`+
 panel('City priority comparison','Commercially screened shortlist; not the six highest scores',`<div class="table-scroll"><table class="brief-table"><thead><tr><th>Review order</th><th>City</th><th>Score /100</th><th>Rank sensitivity</th><th>City GMV /yr</th><th>Orders /day at 10%</th><th>Share for 1 store eq.</th><th>Location model</th></tr></thead><tbody>${shortlist.map((c,i)=>`<tr><td>${i+1}</td><td>${cityButton(c)}</td><td>${score(c)}</td><td>${c.model.rankRange?.join('–')||'—'}</td><td>${cr(c.model.marketBase,1)}</td><td>${band(c.model.scenarios[1].ordersDayLow,c.model.scenarios[1].ordersDayHigh)}</td><td>${band(c.model.oneStoreShareLow,c.model.oneStoreShareHigh,1)}%</td><td><button class="small-link" data-map-city="${esc(c.name)}">${c.name==='Nagpur'?'38-ward model':'Satellite context'} ↗</button></td></tr>`).join('')}</tbody></table></div>`,'','All six: Minutes presence unconfirmed · Share is a planning assumption, not an available market gap')+
 `<div class="analysis-grid">${panel('Nagpur location recommendation','Population-weighted ward model',`<div class="panel-body"><div class="metric-line"><span>First search area</span><b>Ward 17 · Ganeshpeth / Rambagh</b></div><div class="metric-line"><span>Ward baseline population</span><b>${number(LOCATION_DATA.wards[16].population)}</b></div><div class="metric-line"><span>Selected + adjacent wards</span><b>${number(LOCATION_DATA.scenarios[0].oneHopPopulation)} people</b></div><div class="metric-line"><span>Best single-area configuration</span><b>1 of 38 evaluated</b></div><div class="metric-line"><span>Verified store premises</span><b>None selected</b></div><button class="full-link" data-map-city="Nagpur">Open location analysis ↗</button></div>`)}${panel('Investment decision status','No city cleared for a lease commitment',`<div class="panel-body"><div class="metric-line"><span>Commercial screen</span><b>Complete for ${T.stats.rankedCandidates} candidates</b></div><div class="metric-line"><span>Satellite maps</span><b>6 priority cities</b></div><div class="metric-line"><span>Current city competitor shares</span><b>Not disclosed</b></div><div class="metric-line"><span>Peak road-time model</span><b>Not available</b></div><div class="metric-line"><span>Rent and unit economics</span><b>Not established</b></div></div>`)}</div>`;
}

function method(cityId){
 document.getElementById('method-title').textContent='Method & assumptions';
 const c=cityId?byId.get(cityId):null,m=c?.model;
 const sourceRows=T.sources.filter((s,i,a)=>s.url&&a.findIndex(x=>x.id===s.id)===i).map(s=>`<div class="source-row"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.id)}</a><small>${esc(s.publisher||s.type||'Official publication')} ${s.period?'· '+esc(s.period):''}</small><small>${esc(s.verification||s.note||s.limits||s.evidence||'See original document and data export for provenance.')}</small></div>`).join('');
 const trail=c?`<section class="method-section"><h3>${esc(c.name)} — calculation trail</h3><div class="formula-line">Population proxy = ${number(c.pop)} × ${number(c.growthFactor,6)} = ${number(c.populationProxy)}<br>Annual consumption envelope = population proxy × ₹${number(c.coreMpce,2)} × 365 /30 ÷ 10,000,000 = ${cr(c.consumptionCr,2)}${m?`<br>2025 GMV allocation = ${number(c.walletWeight,2)} ÷ ${number(T.model.walletDenominator,2)} × ₹22,180 cr = ${cr(m.market2025,2)}<br>2026 central planning GMV = ${cr(m.market2025,2)} × ${number(T.forecast.growthMid,6)} = ${cr(m.marketBase,2)}<br>10% ambition = ${cr(m.entryBase,2)}<br>Store eq. = ambition × 10,000,000 ÷ (₹691 or ₹508 × 1,089 × 365) = ${band(m.storeLow,m.storeHigh,3)}`:''}</div><p>Original Census population and area: ${esc(B.cities.find(x=>x.id===c.id)?.raw.sourceFile)}; cells ${esc(B.cities.find(x=>x.id===c.id)?.raw.sourceCells.population2011)} / ${esc(B.cities.find(x=>x.id===c.id)?.raw.sourceCells.area2011Km2)}. Population is for the matched ${c.geotype==='UA'?'urban agglomeration':'town'}, not its district.</p><details><summary>Presence and competitor evidence for this city</summary>${[...c.presence,...c.competitors].map(e=>`<div class="source-row">${esc(e.platform||'Flipkart Minutes')} · ${esc(e.status)}<br>${sourceLink(e.source_id)}<small>${esc(e.caution||e.note||'City-level evidence only; not a live service polygon.')}</small></div>`).join('')||'<p>No affirmative evidence in the scoped official-source review. Absence is not established.</p>'}</details></section>`:'';
 document.getElementById('method-body').innerHTML=trail+
 `<section class="method-section"><h3>What this terminal is</h3><p>Commercial research snapshot dated 8 October 2026; ward maps and network comparisons updated 9 October 2026. It provides completed, read-only analysis without requiring data entry. It is a city-prioritisation model; it is not a live Flipkart operating feed. No official affiliation or deployment inside Flipkart is claimed.</p><p>The universe is 942 top-level Census 2011 Class I/II urban agglomerations and towns with at least 50,000 people. It is not an official tier-2/tier-3 list and does not include all current towns. ${T.stats.presenceMarkets} records have matched affirmative Minutes evidence; the company reports more than 150 cities, so the rest are unconfirmed, not absent.</p></section>`+
 `<section class="method-section"><h3>Published fact → model → recommendation</h3><p><b>Published facts:</b> Census 2011 populations, state HCES consumption values, state CMS household participation and company-reported operating benchmarks.</p><p><b>Published estimates:</b> November 2019 state population projections and the company-commissioned Redseer industry estimates/forecasts in official investor documents.</p><p><b>Analyst model:</b> city downscaling, spending allocation, 2026 compound-growth interpolation, share ambitions, score weights and store equivalents.</p><p><b>Recommendation:</b> a conditional one-store pilot business case where the base ambition reaches one lower-basket throughput equivalent. This is not a site or capital approval.</p></section>`+
 `<section class="method-section"><h3>How the model works</h3>${T.model.assumptions.map((a,i)=>`<p><b>${String(i+1).padStart(2,'0')}.</b> ${esc(a)}</p>`).join('')}<p>2011 state boundaries are preserved. Andhra Pradesh/Telangana and Jammu &amp; Kashmir/Ladakh use explicit pooled proxies weighted by projected successor-state urban population. Merged Dadra &amp; Nagar Haveli / Daman &amp; Diu use the combined series.</p></section>`+
 `<section class="method-section"><h3>2026 interpolation and residual demand</h3><div class="formula-line">Published nonmetro GMV: 2025 ≈₹22,180 cr; 2030 forecast ₹1,37,700–2,11,700 cr<br>2026 low = 22,180 × (137,700 /22,180)^(1/5) = ${cr(T.forecast.pool2026LowCr,1)}<br>2026 high = 22,180 × (211,700 /22,180)^(1/5) = ${cr(T.forecast.pool2026HighCr,1)}<br>Central growth factor = mean(${number(T.forecast.growthLow,6)}, ${number(T.forecast.growthHigh,6)})<br>2025 allocation retained outside named markets: ${cr(T.stats.residualPoolCr,1)}</div><p>The full national pool is not forced into the 942-city dataset. State-based denominators retain other urban demand. State projection totals do not exactly equal the report’s India total; calculations consistently use the state totals. Metro boundaries remain a disclosed approximation.</p><p>HCES core basket = food total − served processed food − prepared tea/coffee/juice + toiletries + household consumables. State consumption is not city income. The all-category quick-commerce pool is allocated using this core-basket proxy; a city's non-grocery mix may differ.</p></section>`+
 `<section class="method-section"><h3>What was checked twice</h3><p>13,268 Census numeric cells: workbook extraction versus raw XML, zero discrepancies. Population corroborates against matched PCA geography for 836 markets. Another 766 HCES cells and 342 projection values passed separate extraction checks. The two checks are not two independent surveys.</p><p>Company benchmarks retain their periods, definitions and individual verification notes. Some qualitative planning sources were available only as official indexed extracts; their access limitations are retained in the export. The model's judgments cannot be verified as observed facts.</p><details><summary>Benchmark definitions and verification</summary>${T.benchmarks.metrics.map(x=>`<div class="source-row"><b>${esc(x.label)}: ${number(x.value,Number.isInteger(x.value)?0:3)} ${esc(x.unit)}</b><small>${esc(x.period)} · ${esc(x.basis)}</small><small>${esc(x.checks.join(' | '))}</small><small>${esc(x.note)}</small></div>`).join('')}</details></section>`+
 `<section class="method-section"><h3>Spatial planning</h3><p>Nagpur now includes an exact ward-level location-allocation screen, using 38 final municipal wards. It selects search areas, not premises. Road times, rents and delivery catchments remain unverified.</p><button class="export-button" id="location-method">Open location model details ↗</button></section><section class="method-section"><h3>Additional parameters for the next operating layer</h3><p>The research dictionary includes ${B.parameters.length} candidate parameters. They remain unscored where comparable official city measurements are missing; adding empty or speculative metrics would create false precision.</p><details><summary>Explore the parameter dictionary</summary>${B.parameters.map(p=>`<div class="source-row"><b>${esc(p.name||p.parameter||p.id)}</b><small>${esc(p.why||p.whyItMatters||'')}</small><small>${esc(p.caution||'')}</small></div>`).join('')}</details></section>`+
 `<section class="method-section"><h3>Audit library</h3><p>Sources are kept here so the operating views stay focused. Numeric results in the export retain their labels, periods and assumptions.</p><details><summary>Open ${T.sources.length} source records</summary>${sourceRows}</details><button class="export-button" id="download-audit" style="margin-top:18px">Download model &amp; evidence JSON ↓</button></section>`;
 document.getElementById('method-dialog').showModal();
}

function overview(){return atlasOverview();}
function locations(){return atlasLocations();}
function render(){
 const views={overview,markets,city,brief,locations};main.innerHTML=views[state.view]();
 document.querySelectorAll('nav [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.setAttribute('aria-current',b.dataset.view===state.view?'page':'false');});
 document.getElementById('view-label').textContent=({overview:'Expansion desk',markets:'Market universe',city:'City intelligence',locations:'Store locations',brief:'Decision brief'})[state.view];
 document.title=state.view==='city'?`${byId.get(state.city).name} — Minutes Intelligence`:'Minutes — Market Intelligence';
}
function navigate(view,id){
 if(id&&!byId.has(id)){toast('City not found in the research universe.');return false;}
 state.view=view;if(id)state.city=id;
 const hash=view==='city'?'city/'+state.city:view;
 if(location.hash.slice(1)!==hash)history.replaceState(null,'','#'+hash);
 render();window.scrollTo({top:0,behavior:'instant'});return true;
}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800);}
function download(name,body,type){const u=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
function exportCsv(){
 const cols=['Census ID','City','2011 state','Geography','Minutes evidence status','Metro proxy exclusion','Census2011 population','2025 population proxy','Census2011 households','Census2011 area km2','Census2011 density','Census2011 main other-worker share percent','State core MPCE 2023-24 per30days','State online-food HH proxy percent2025','Screening score','Candidate rank','CY2025 GMV allocation INRcr','CY2026 planning GMV INRcr','2026 sensitivity low INRcr','2026 sensitivity high INRcr','10percent entrant ambition INRcr','Planning stores lower','Planning stores upper','One store share lower percent','One store share upper percent','Recommended sequence','Snapshot','Interpretation'];
 const lines=[cols,...T.cities.map(c=>[c.id,c.name,c.state,c.geotype,presenceLabel(c),c.metro,c.pop,c.populationProxy,c.households,c.area,c.density,c.otherWorkerPct,c.coreMpce,c.digitalPct,c.model?.score,c.model?.rank,c.model?.market2025,c.model?.marketBase,c.model?.marketLow,c.model?.marketHigh,c.model?.entryBase,c.model?.storeLow,c.model?.storeHigh,c.model?.oneStoreShareLow,c.model?.oneStoreShareHigh,c.networkText||'Metro outside model',T.snapshot,'Analyst scenarios, not measured city sales; unknown is not absent; stores use valuation-convention sensitivity, not GMV-to-NOV conversion'])];
 const safe=v=>'"'+String(v??'').replace(/"/g,'""')+'"';download('Minutes-market-analysis-2026-10-08.csv','\uFEFF'+lines.map(row=>row.map(safe).join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('Market analysis exported with model labels.');
}
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a');if(!b)return;
 if(b.dataset.city){navigate('city',b.dataset.city);return;}
 if(b.dataset.view){navigate(b.dataset.view);return;}
 if(b.dataset.filter){state.filter=b.dataset.filter;state.page=0;render();return;}
 if(b.dataset.cityMethod){method(b.dataset.cityMethod);return;}
 if(b.id==='method-open'||b.id==='mobile-method')method(state.view==='city'?state.city:null);
 if(b.id==='method-close')document.getElementById('method-dialog').close();
 if(b.id==='export')exportCsv();
 if(b.id==='prev-page'){state.page=Math.max(0,state.page-1);render();}
 if(b.id==='next-page'){state.page++;render();}
 if(b.id==='download-audit')download('Minutes-model-and-evidence-2026-10-09.json',JSON.stringify({terminal:T,census:B.metadata,rawCities:B.cities,parameterDictionary:B.parameters,spatialModel:LOCATION_DATA,localCompetitorEvidence:LOCAL_COMPETITION,geographyUpdated:"2026-10-09",cityWardMaps:CITY_WARDS,cityNetworks:CITY_NETWORKS,satelliteAnalysis:{...SATELLITE_DATA,satellite:undefined,landcover:undefined,builtup:undefined},priorityMapSources:PRIORITY_MAPS.cities.map(({satellite,landcover,...meta})=>meta)},null,2),'application/json');
 if(b.id==='print-brief')window.print();
});
document.addEventListener('change',e=>{if(e.target.id==='state-filter'){state.region=e.target.value;state.page=0;render();}if(e.target.id==='sort-filter'){state.sort=e.target.value;state.page=0;render();}});
document.getElementById('method-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}});
function route(){const hash=location.hash.slice(1);if(hash.startsWith('city/')){const id=hash.slice(5);if(byId.has(id)){state.city=id;state.view='city';}else{state.view='overview';toast('Unknown city link. Showing the overview.');}}else if(['overview','markets','city','brief','locations'].includes(hash))state.view=hash;render();}
window.addEventListener('hashchange',route);route();
// Native browser tools expose the same read-only evidence and navigation as the UI.
if(navigator.modelContext?.registerTool){
 try{
 navigator.modelContext.registerTool({name:'read_market_intelligence',description:'Read this research snapshot and precomputed market scenarios. Unknown presence is not absence; modelled values are not actual sales.',inputSchema:{type:'object',properties:{city_id:{type:'string'}},required:['city_id'],additionalProperties:false},execute:async({city_id})=>{const c=byId.get(city_id);return {content:[{type:'text',text:JSON.stringify(c?{city:c,snapshot:T.snapshot,assumptions:T.model.assumptions}:{error:'Unknown city ID'})}]};}});
 navigator.modelContext.registerTool({name:'open_market_intelligence',description:'Open a city dossier in this read-only dashboard.',inputSchema:{type:'object',properties:{city_id:{type:'string'}},required:['city_id'],additionalProperties:false},execute:async({city_id})=>({content:[{type:'text',text:navigate('city',city_id)?'Opened city dossier.':'Unknown city ID.'}]})});
 }catch(err){console.info('Optional browser tool registration unavailable.');}
}
